__author__ = 'nikita_kartashov'

from approximate_matching import all_approximate_occurences


def count_with_mismatches(text, pattern, mismatches):
    return len(list(all_approximate_occurences(text, pattern, mismatches)))

if __name__ == '__main__':
    TEXT = 'ACATTGCCGCATCTGCATACTGCCCTTGGGCGGTATAGTGAGCTTGATGCTACCGCAGGGGTATTAGATGACGCATTCCTAAGGAGCCGACGCAACTGGGAGCCGGGGGCCTTGTGCAACGTTAACCTATAACTTGCCCTTCGAAGTTCGGACCTGTGACTAAAGTACTACCCGTTCCTCCGAATAAGTTTGTACCTAGTGGTCAAAGTTGACTTGGAAGCAACTACGAGGGGTGGCAAGGGCGAACCCTATGGCGGTTATTCTGCCAAAGAGGATGAGACGATAATAATTGGCTTTGTACCCTGGCCTGCACATAATGCATAATTGGGTCTACACGGGTTCAGACACACCTTAAATACTCCCTTCGTGCTTACTAACTC'
    PATTERN = 'GGCAAG'
    mismatches = 3
    print(count_with_mismatches(TEXT, PATTERN, mismatches))


